"""add payment orchestration

Revision ID: 0013_payment_orchestration
Revises: 0012_consumed_step_up_proofs
Create Date: 2026-08-15 11:58:37.464501
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0013_payment_orchestration'
down_revision: str | None = '0012_consumed_step_up_proofs'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS payments")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('business_reference', sa.String(length=128), nullable=False),
    sa.Column('payer_user_id', sa.UUID(), nullable=True),
    sa.Column('payee_user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('refunded_amount', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('requires_action','processing','succeeded','failed','cancelled','partially_refunded','refunded')", name='ck_payment_intents_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_intents_amount_positive'),
    sa.CheckConstraint('refunded_amount >= 0 AND refunded_amount <= amount', name='ck_payment_intents_refunded_amount'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'idempotency_key', name='uq_payment_intents_client_idempotency'),
    schema='payments'
    )
    op.create_index('idx_payment_intents_business', 'payment_intents', ['client_id', 'business_reference'], unique=False, schema='payments')
    op.create_index('idx_payment_intents_status_updated', 'payment_intents', ['status', 'updated_at'], unique=False, schema='payments')
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('processor', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('network', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_reference', sa.String(length=160), nullable=True),
    sa.Column('provider_status', sa.String(length=80), nullable=True),
    sa.Column('next_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','requires_action','processing','succeeded','failed','cancelled','unknown')", name='ck_payment_attempts_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_attempts_amount_positive'),
    sa.CheckConstraint('attempt_number > 0', name='ck_payment_attempt_number_positive'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payments.payment_intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_intent_id', 'attempt_number', name='uq_payment_attempt_number'),
    schema='payments'
    )
    op.create_index('idx_payment_attempts_intent', 'payment_attempts', ['payment_intent_id', 'attempt_number'], unique=False, schema='payments')
    op.create_index('idx_payment_attempts_status_updated', 'payment_attempts', ['status', 'updated_at'], unique=False, schema='payments')
    op.create_index('uq_payment_attempt_provider_reference', 'payment_attempts', ['processor', 'provider_reference'], unique=True, schema='payments', postgresql_where=sa.text('provider_reference IS NOT NULL'))
    op.create_index('uq_payment_attempt_success', 'payment_attempts', ['payment_intent_id'], unique=True, schema='payments', postgresql_where=sa.text("status = 'succeeded'"))
    op.create_table('provider_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('processor', sa.String(length=64), nullable=False),
    sa.Column('event_key', sa.String(length=180), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('received','processed','ignored','failed')", name='ck_provider_events_status'),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payments.payment_attempts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processor', 'event_key', name='uq_provider_event_key'),
    schema='payments'
    )
    op.create_index('idx_provider_events_status_created', 'provider_events', ['status', 'created_at'], unique=False, schema='payments')
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('processor', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('provider_reference', sa.String(length=160), nullable=True),
    sa.Column('provider_status', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','processing','succeeded','failed')", name='ck_refunds_status'),
    sa.CheckConstraint('amount > 0', name='ck_refunds_amount_positive'),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payments.payment_attempts.id'], ),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payments.payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'idempotency_key', name='uq_refunds_client_idempotency'),
    schema='payments'
    )
    op.create_index('idx_refunds_intent_created', 'refunds', ['payment_intent_id', 'created_at'], unique=False, schema='payments')
    op.create_index('uq_refund_provider_reference', 'refunds', ['processor', 'provider_reference'], unique=True, schema='payments', postgresql_where=sa.text('provider_reference IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_refund_provider_reference', table_name='refunds', schema='payments', postgresql_where=sa.text('provider_reference IS NOT NULL'))
    op.drop_index('idx_refunds_intent_created', table_name='refunds', schema='payments')
    op.drop_table('refunds', schema='payments')
    op.drop_index('idx_provider_events_status_created', table_name='provider_events', schema='payments')
    op.drop_table('provider_events', schema='payments')
    op.drop_index('uq_payment_attempt_success', table_name='payment_attempts', schema='payments', postgresql_where=sa.text("status = 'succeeded'"))
    op.drop_index('uq_payment_attempt_provider_reference', table_name='payment_attempts', schema='payments', postgresql_where=sa.text('provider_reference IS NOT NULL'))
    op.drop_index('idx_payment_attempts_status_updated', table_name='payment_attempts', schema='payments')
    op.drop_index('idx_payment_attempts_intent', table_name='payment_attempts', schema='payments')
    op.drop_table('payment_attempts', schema='payments')
    op.drop_index('idx_payment_intents_status_updated', table_name='payment_intents', schema='payments')
    op.drop_index('idx_payment_intents_business', table_name='payment_intents', schema='payments')
    op.drop_table('payment_intents', schema='payments')
    op.execute("DROP SCHEMA IF EXISTS payments CASCADE")
    # ### end Alembic commands ###
