"""add payment outbox

Revision ID: 0014_payment_outbox
Revises: 0013_payment_orchestration
Create Date: 2026-08-15 12:49:02.123044
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0014_payment_outbox'
down_revision: str | None = '0013_payment_orchestration'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','delivered','dead_letter')", name='ck_payment_outbox_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='payments'
    )
    op.create_index('idx_payment_outbox_pending', 'outbox_events', ['status', 'next_attempt_at', 'created_at'], unique=False, schema='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_outbox_pending', table_name='outbox_events', schema='payments')
    op.drop_table('outbox_events', schema='payments')
    # ### end Alembic commands ###
