"""add fund payment orders

Revision ID: 0426796797d5
Revises: 0014_payment_outbox
Create Date: 2026-08-15 13:57:13.923022
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0426796797d5'
down_revision: str | None = '0014_payment_outbox'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_event_inbox',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    schema='fund'
    )
    op.create_table('payment_orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('operation_type', sa.String(length=30), nullable=False),
    sa.Column('business_reference', sa.String(length=128), nullable=False),
    sa.Column('payer_user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("operation_type IN ('investment','loan_repayment')", name='ck_fund_payment_order_operation'),
    sa.CheckConstraint("status IN ('requires_action','processing','succeeded','failed','cancelled','unknown')", name='ck_fund_payment_order_status'),
    sa.CheckConstraint('amount > 0', name='ck_fund_payment_order_amount'),
    sa.ForeignKeyConstraint(['campaign_id'], ['fund.campaigns.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['fund.loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_fund_payment_order_idempotency'),
    sa.UniqueConstraint('payment_intent_id', name='uq_fund_payment_order_intent'),
    schema='fund'
    )
    op.create_index('idx_fund_payment_orders_user', 'payment_orders', ['payer_user_id', 'created_at'], unique=False, schema='fund')
    op.add_column('investments', sa.Column('payment_intent_id', sa.UUID(), nullable=True), schema='fund')
    op.alter_column('investments', 'wallet_transaction_id',
               existing_type=sa.UUID(),
               nullable=True,
               schema='fund')
    op.create_unique_constraint('uq_fund_investment_payment_intent', 'investments', ['payment_intent_id'], schema='fund')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fund_investment_payment_intent', 'investments', schema='fund', type_='unique')
    op.alter_column('investments', 'wallet_transaction_id',
               existing_type=sa.UUID(),
               nullable=False,
               schema='fund')
    op.drop_column('investments', 'payment_intent_id', schema='fund')
    op.drop_index('idx_fund_payment_orders_user', table_name='payment_orders', schema='fund')
    op.drop_table('payment_orders', schema='fund')
    op.drop_table('payment_event_inbox', schema='fund')
    # ### end Alembic commands ###
