"""harden payment outbox claims

Revision ID: 22eb39b4d210
Revises: a560f55cc5d9
Create Date: 2026-08-15 14:23:32.464112
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '22eb39b4d210'
down_revision: str | None = 'a560f55cc5d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True), schema='payments')
    op.drop_constraint('ck_payment_outbox_status', 'outbox_events', schema='payments', type_='check')
    op.create_check_constraint(
        'ck_payment_outbox_status',
        'outbox_events',
        "status IN ('pending','delivering','delivered','dead_letter')",
        schema='payments',
    )
    op.drop_index('idx_payment_outbox_pending', table_name='outbox_events', schema='payments')
    op.create_index(
        'idx_payment_outbox_pending',
        'outbox_events',
        ['status', 'next_attempt_at', 'locked_at', 'created_at'],
        unique=False,
        schema='payments',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE payments.outbox_events SET status = 'pending' WHERE status = 'delivering'")
    op.drop_constraint('ck_payment_outbox_status', 'outbox_events', schema='payments', type_='check')
    op.create_check_constraint(
        'ck_payment_outbox_status',
        'outbox_events',
        "status IN ('pending','delivered','dead_letter')",
        schema='payments',
    )
    op.drop_index('idx_payment_outbox_pending', table_name='outbox_events', schema='payments')
    op.create_index(
        'idx_payment_outbox_pending',
        'outbox_events',
        ['status', 'next_attempt_at', 'created_at'],
        unique=False,
        schema='payments',
    )
    op.drop_column('outbox_events', 'locked_at', schema='payments')
    # ### end Alembic commands ###
