"""add payment financial ledger

Revision ID: a560f55cc5d9
Revises: 0426796797d5
Create Date: 2026-08-15 14:17:07.760034
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a560f55cc5d9'
down_revision: str | None = '0426796797d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_journals',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_reference', sa.String(length=180), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_financial_journal_amount'),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payments.payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'event_reference', name='uq_financial_journal_event'),
    schema='payments'
    )
    op.create_index('idx_financial_journal_intent', 'financial_journals', ['payment_intent_id', 'created_at'], unique=False, schema='payments')
    op.create_table('financial_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('account', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('debit','credit')", name='ck_financial_entry_direction'),
    sa.CheckConstraint('amount > 0', name='ck_financial_entry_amount'),
    sa.ForeignKeyConstraint(['journal_id'], ['payments.financial_journals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='payments'
    )
    op.create_index('idx_financial_entry_account', 'financial_entries', ['account', 'created_at'], unique=False, schema='payments')
    op.create_index('idx_financial_entry_journal', 'financial_entries', ['journal_id'], unique=False, schema='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_financial_entry_journal', table_name='financial_entries', schema='payments')
    op.drop_index('idx_financial_entry_account', table_name='financial_entries', schema='payments')
    op.drop_table('financial_entries', schema='payments')
    op.drop_index('idx_financial_journal_intent', table_name='financial_journals', schema='payments')
    op.drop_table('financial_journals', schema='payments')
    # ### end Alembic commands ###
